### ISSUE TITLE
fatal error: esp_a2dp_api.h: No such file or directory

### ISSUE THREAD

**Issue by allenck** [whyengineer/esp32_snow#2]
I am trying to compile this project, example 'web_server',  but am getting errors finding several header files.
The project would not compile using esp-idf git checkout  release/v3.0. It gets an error compiling the bootloader. 

` make[2]: *** No rule to make target '/home/allen/esp/esp-idf/components/bootloader/subproject/components/micro-ecc/component.mk'.  Stop.`
However  git checkout  release/v3.3 corrects this but now I get `/home/allen/Downloads/esp32_snow/components/bt_speaker/include/bt_app_av.h:19:26: fatal error: esp_a2dp_api.h: No such file or directory
`
I can correct this error and others like it by changing #include "esp_a2dp_api.h" to #include "/home/allen/esp/esp-idf/components/bt/bluedroid/api/include/api/esp_a2dp_api.h"

This is obviously a solution that allows the project to be downloaded by others. What I need to do is specify the location of esp_a2dp_api.h, 

I tried adding this line to the component.mk file : 

 `COMPONENT_ADD_INCLUDEDIRS:=/home/allen/esp/esp-idf/components/bt/bluedroid/api/include/api` to no effect. 

What must be done to correct the project so that it can find the header files?

**Comment by whyengineer** [comment]
hi, a2dp is a classic BT feature, if you enable BT and Classic BT in menuconfig, this header file would be join in compiler search path.

**Comment by allenck** [comment]
Thanks. That solved it.
